name: YouTube RSS Daily Email

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  send-youtube-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run YouTube RSS script
        env:
          GMAIL_SENDER:       ${{ secrets.GMAIL_SENDER }}
          GMAIL_RECEIVER:     ${{ secrets.GMAIL_RECEIVER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python Yt_rss.py
